---
- include_vars: "group_vars/{{ system_type }}.yml"
  when: system_type is defined

- name: "Install Galicaster Profiles"
  template: >
         src=profiles/{{ item }}
         dest=/etc/galicaster/profiles/{{ item }}
         group={{ ca_username }}
         owner={{ ca_username }}
  with_items:
         - dual-v4l2-split.ini
         - v4l2-split.ini
         - v4l2-usb.ini
  # notify: restart galicaster
  tags:
         - galicaster
         - galicaster_config
         - galicaster_profiles
